### numpy - 다차원 배열(행렬)을 쉽게 처리하고 효율적으로 사용할 수 있도록 지원하는 파이썬 라이브러리이다 

In [26]:
import numpy as np

# 일반 배열(리스트)
a = [3, 1, 2, 'a', 'b']
print(a)

arr = [[1,2], [3,4, 5]]
print(arr)

x = np.array([3, 1, 2])
print(x)
type(x)

#내부 배열의 원소 개수가 같아야 한다.
x2 = np.array([[1, 2], [3, 4, 5]]) 
print(x2)
type(x2)

[3, 1, 2, 'a', 'b']
[[1, 2], [3, 4, 5]]
[3 1 2]


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [30]:
import numpy as np

list1 = [1, 3, 5]
list2 = [2, 4, 6]
list1 + list2

nd1 = np.array([1, 3, 5])
nd2 = np.array([2, 4, 6])
nd1 + nd2

array([ 3,  7, 11])

In [72]:
# numpy 관련 속성 및 메서드
# ndim : 배열의 차원 수를 반환
# shape : 배열의 각 차원의 크기를 튜플 형태로 표현
ndarr1 = np.array([[1, 2, 3], [4, 5, 6]])
print(str(ndarr1.ndim)  + "차원")
print(f'{ndarr1.shape} 형태')

#arange([start], stop, [step]) - 특정 배열을 만들어줌
print(np.arange(5))
print(np.arange(5, 10))
print(np.arange(5, 10, 2))

# 행렬의 평탄화 작업 - N차원을 1차원 배열로 변환
ndarr2 = np.array([[6, 3], [5, 2], [4, 1]])
print(ndarr2)
ndarr2.flatten()

# 배열의 차원을 변경
print(ndarr2.shape)
ndarr2.reshape(2, 3)

# m x n 크기의 0행렬
print(np.zeros((2, 2)))
# m x n 크기의 유닛 행렬
print(np.ones((2, 3)))

2차원
(2, 3) 형태
[0 1 2 3 4]
[5 6 7 8 9]
[5 7 9]
[[6 3]
 [5 2]
 [4 1]]
(3, 2)
[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [36]:
import numpy as np

# 10개의 0으로 채워진 array를 만들어 주세요
an1 = np.zeros(10)
print(an1)

# 1번에서 만들어진 array에서 5번째 값을 1로 바꿔주세요
an2 = an1
an2[4] = 1
print(an2)

# 10부터 30까지의 수로 이루어진 array를 만들어 주세요
an3 = np.arange(10, 31)
print(an3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]
