In [11]:
# 넘파이 배열의 기본 요소
import numpy as np

array = np.array([[1,2,3],
                  [4,5,6]])

print(array)
print(array.ndim)
print(array.shape)
print(array.dtype)
print(type(array))

[[1 2 3]
 [4 5 6]]
2
(2, 3)
int32
<class 'numpy.ndarray'>


In [19]:
# 넘파이 배열 생성
array1 = np.array([[1,2,3], [4,5,6]])
array2 = np.array([1,2,3], dtype=complex, ndmin=3)
array3 = np.array(array1, copy=False)
array4 = np.array(np.mat('1 2; 3 4'), subok=True)

print(array1)
print(array2)
print(array3)
print(array4)
print(type(array4)) #행렬

[[1 2 3]
 [4 5 6]]
[[[1.+0.j 2.+0.j 3.+0.j]]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]]
<class 'numpy.matrix'>


In [45]:
# 개별 단위 요소에 접근하기
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([[1, 2],
                [3, 4]])
arr3 = np.array([[[1, 2], 
                  [3, 4]],
                 [[5, 6], 
                  [7, 8]]])

print(arr1[-1])
print(arr2[0][1])
print(arr3[1][0][1]) #첫번째 페이지의 두번째 행과 두번째 열에 접근

3
2
6


In [49]:
# 배열의 블록 단위 요소에 접근하기
import numpy as np

array = np.array([[[1, 2], 
                  [3, 4]],
                 [[5, 6], 
                  [7, 8]]])

# 배열의 첫 번째 페이지의 행렬에서 짝수 요소만 출력
for i in array[0]:
    for j in i:
        if j % 2 == 0:
            print(j)

array1 = 

2
4


In [57]:
# 관심 역역

array = np.zeros((1280, 1920, 3), np.uint8)

x, y, w, h = 100, 100, 300, 300
roi = array[x: x + w, y: y + h]

print(array.shape)
print(roi.shape)
# print(array)
print(roi)

(1280, 1920, 3)
(300, 300, 3)
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [1]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value

    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [5]:
max??

Docstring:
max(iterable, *[, default=obj, key=func]) -> value
max(arg1, arg2, *args, *[, key=func]) -> value

With a single iterable argument, return its biggest item. The
default keyword-only argument specifies an object to return if
the provided iterable is empty.
With two or more arguments, return the largest argument.
Type:      builtin_function_or_method

In [13]:
import numpy as np
x = np.array([[1,2], [3,4], [5,6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
x.flatten()

array([1, 2, 3, 4, 5, 6])