### numpy - 다차원 배열을 쉽게 처리하고 효율적으로 사용할 수 있는 파이썬 라이브러리

In [14]:
import numpy as np

# 일반 배열(리스트)
a = [3, 1, 2]
print(a)

a2 = [[1,2], [3,4,5]]
print(a2)


# numpy에서 사용하는 배열
x = np.array([3, 1, 2])
print(x)

#내부 배열의 원소 개수가 같아야 한다.
x2 = np.array([[1, 2], [3, 4]]) 
print(x2)

[3, 1, 2]
[[1, 2], [3, 4, 5]]
[3 1 2]
[[1 2]
 [3 4]]


In [16]:
import numpy as np

list1 = [1, 3, 5]
list2 = [2, 4, 6]
print(list1 + list2)

nd1 = np.array([1, 3, 5])
nd2 = np.array([2, 4, 6])
print(nd1 + nd2)

[1, 3, 5, 2, 4, 6]


array([ 3,  7, 11])