### Numpy(넘파이)

In [40]:
import numpy as np

# 수학 관련 함수
n1 = np.sum([1, 2, 3])  #합계 
print(n1)
n2 = np.mean([1, 2, 3, 4]) #평균 
print(n2)
n3 = np.square(9) #제곱수 
print(n3)
n4 = np.sqrt(4) #제곱근 
print(n4)

6
2.5
81
2.0


In [41]:
import numpy as np

# 배열(리스트) 관련 함수
# 1차원 배열
x = np.array([1, 2, 3])
print(x)
print(type(x)) # 타입 
print(x.shape) # 크기 

# 인덱싱 및 슬라이싱
print(x[0])
print(x[2])
print(x[-1])
print(x[0:3])
print(x[:])
print(x[:-1])

# 2차원 배열
d2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(d2)
print(d2.shape)

# 인덱싱 및 슬라이싱
print(d2[0, 0])
print(d2[1, 1])
print(d2[0:, 0:])
print(d2[1:, 1:])

# arange(시작값, 종료값, 증감값) - (종료값-1)
a = np.arange(10)
print(a)
b = np.arange(0, 10, 1)
print(b)
c = np.arange(0, 10, 2)
print(c)

# 1차원 배열을 2차원 배열
a2 = a.reshape(2,5)
print(a2)

# 2차원을 1차원 배열로
a3 = a2.flatten()
print(a3)

[1 2 3]
<class 'numpy.ndarray'>
(3,)
1
3
3
[1 2 3]
[1 2 3]
[1 2]
[[1 2 3]
 [4 5 6]]
(2, 3)
1
5
[[1 2 3]
 [4 5 6]]
[[5 6]]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]


In [38]:
import numpy as np

# 결측치(nan)
a = np.nan
print(a)
print(type(a))

# 0 생성
a1 = np.zeros((3, 3))
print(a1)

# 1 생성
a2 = np.ones((2, 3))
print(a2)

a3 = np.ones((2, 3), dtype=int)
print(a3)

nan
<class 'float'>
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]]
