In [1]:
import numpy as np

n1 = np.sum([1, 2, 3])
n1

6

In [24]:
x = np.array([1, 2, 3])
print(x)
print(x.shape)

print(x[0])
print(x[2])
print(x[-1])
print(x[0:3])
print(x[:])
print(x[:-1])

[1 2 3]
(3,)
1
3
3
[1 2 3]
[1 2 3]
[1 2]


In [23]:
d2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(d2)
print(d2.shape)

print(d2[0, 0])
print(d2[1, 1])
print(d2[0:, 0:])
print(d2[1:, 1:])

[[1 2 3]
 [4 5 6]]
(2, 3)
1
5
[[1 2 3]
 [4 5 6]]
[[5 6]]


In [31]:
a = np.arange(10)
print(a)
b = np.arange(0, 10, 1)
print(b)
c = np.arange(0, 10, 2)
print(c)

a2 = a.reshape(2,5)
print(a2)

a3 = a2.flatten()
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]


In [36]:
import numpy as np

a = np.nan
print(a)
print(type(a))

a1 = np.zeros((3, 3))
print(a1)

a2 = np.ones((2, 3))
print(a2)

a3 = np.ones((2, 3), dtype=int)
print(a3)

nan
<class 'float'>
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]]
