In [1]:
import numpy as np #numpy 라이브러리 import
x = np.array([3, 1, 2]) #np.array : ndarray 타입의 배열 생성
print(x) # x 성분 출력
type(x) # x의 type 확인

[3 1 2]


numpy.ndarray

In [11]:
print(x.ndim)
print(x.shape)

1
(3,)


In [12]:
y = np.array([3, 4, 5])

print(x+y)
print(x-y)
print(x*y)
print(x/y)

[6 5 7]
[ 0 -3 -3]
[ 9  4 10]
[1.   0.25 0.4 ]


In [28]:
print(np.zeros((2,2)))  # 영행렬 생성
print(np.ones((2,3)))  # 유닛행렬
print(np.full((2,3), 5)) # 모든 원소가 5인 2*3행렬
print(np.eye(3)) # 단위행렬

[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5]
 [5 5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
# list와 ndarray의 차이점
# 1. list는 원소로 여러가지 자료형을 허용하고, ndarray는 한가지 자료형만 허용한다.

a = [1, 2, 'a', 'b'] # 1, 2는 숫자형, 'a', 'b'는 문자열
b = np.array([1, 2, 'a', 'b']) # '1', '2', 'a', 'b'의 문자열로 전환
print(a)
print(b)

[1, 2, 'a', 'b']
['1' '2' 'a' 'b']


In [9]:
a = [1, 2, 'a', 'b'] 
b = np.array([1, 2, 'a', 'b'])
print(a)
print(b)

[1, 2, 'a', 'b']
['1' '2' 'a' 'b']


In [16]:
# list와 ndarray의 차이점
# 2. list는 내부 배열의 원소의 개수가 달라도 되고, 
# ndarray는 내부 배열의 원소가 같아야 한다.

c = [[1], [2, 3], [4, 5, 6]] 
d = np.array([[1], [2, 3], [4, 5, 6]])

C:\Users\Lily\AppData\Local\Temp\ipykernel_37604\2524811967.py:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  d = np.array([[1], [2, 3], [4, 5, 6]])


In [19]:
e = np.array([[1, 2], [3, 4], [5, 6]])
print(e)

[[1 2]
 [3 4]
 [5 6]]


In [20]:
print(c)

[[1], [2, 3], [4, 5, 6]]


In [22]:
list1 = [1, 3, 5]
list2 = [2, 4, 6]
list1 + list2

[1, 3, 5, 2, 4, 6]

In [10]:
list1 = [1, 3, 5]
list2 = [2, 4, 6]
print(list1 + list2)
print(list1 * 3)
# print(list1 + 3) #불가
# list1 - list2  #불가
# list1 * list2  #불가
# list1 / list2  #불가

[1, 3, 5, 2, 4, 6]
[1, 3, 5, 1, 3, 5, 1, 3, 5]


In [20]:
ndarray1 = np.array([1, 3, 5])
ndarray2 = np.array([2, 4, 6])
print(ndarray1 + ndarray2)
print(ndarray1 - ndarray2)
print(ndarray1 * ndarray2)
print(ndarray1 / ndarray2)
print("-------------------------")
print(ndarray1 + 3)
print(ndarray1 - 3)
print(ndarray1 * 3)
print(ndarray1 / 3)

[ 3  7 11]
[-1 -1 -1]
[ 2 12 30]
[0.5        0.75       0.83333333]
-------------------------
[4 6 8]
[-2  0  2]
[ 3  9 15]
[0.33333333 1.         1.66666667]


In [21]:
list3 = [1, 3, 5]
list4 = [2, 4]
print(list3 + list4)

[1, 3, 5, 2, 4]


In [22]:
ndarray3 = np.array([1, 3, 5])
ndarray4 = np.array([2, 4])
# print(ndarray3 + ndarray4) # 오류 발생

In [24]:
ndarray3.shape

(3,)

In [27]:
ndarray5 = np.array([[1, 2, 3], [4, 5, 6]])
ndarray5.shape

(2, 3)

In [29]:
######################### numpy 관련 속성 및 메소드 ##########################

In [31]:
ndarray6 = np.array([[1, 2, 3], [4, 5, 6]])
ndarray6.ndim

2

In [33]:
ndarray6.shape

(2, 3)

In [ ]:
###### numpy dot 메소드 ######

In [47]:
np.dot(4, 2)

8

In [38]:
ndar1 = np.array([1, 2, 3])
ndar2 = np.array([4, 5, 6])
print(np.dot(ndar1, ndar2)) # 32
print(np.dot(ndar1, ndar2.T)) # 32

32
32


In [43]:
ndar1 = np.array([[1, 2], [3, 4]])
ndar2 = np.array([[1, 2], [3, 4]])
print(np.dot(ndar1, ndar2)) 

[[ 7 10]
 [15 22]]


In [48]:
###### numpy matmul 메소드 ######

In [49]:
ndar1 = np.array([[1, 2], [3, 4]])
ndar2 = np.array([[1, 2], [3, 4]])
print(np.matmul(ndar1, ndar2)) 

[[ 7 10]
 [15 22]]


In [52]:
ndar1 = np.array([[1, 2, 3], [4, 5, 6]])
ndar2 = np.array([[6, 3], [5, 2], [4, 1]])
print(np.matmul(ndar1, ndar2)) 

[[28 10]
 [73 28]]


In [55]:
ndar1 = np.array([1, 2, 3])
ndar2 = np.array([[6, 3], [5, 2], [4, 1]])
print(np.matmul(ndar1, ndar2)) 

[28 10]


In [56]:
print(np.zeros((2,2)))  # 영행렬 생성

[[0. 0.]
 [0. 0.]]


In [57]:
print(np.ones((2,3)))  # 유닛행렬

[[1. 1. 1.]
 [1. 1. 1.]]


In [58]:
print(np.full((2,3), 5)) # 모든 원소가 5인 2*3행렬

[[5 5 5]
 [5 5 5]]


In [59]:
print(np.eye(3)) # 단위행렬

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
ndarr = np.array([[6, 3], [5, 2], [4, 1]])
ndarr.flatten()

array([6, 3, 5, 2, 4, 1])

In [7]:
print(ndarr.shape)
ndarr.reshape(2,3)

(3, 2)


array([[6, 3, 5],
       [2, 4, 1]])

In [72]:
ndarr = np.array([[6, 3], [5, 2], [4, 1]])
ndarr_cond = ndarr > 4

for i in ndarr_cond.flatten():
    if(i): 
        print("참")
    else: 
        print("거짓")

참
거짓
참
거짓
거짓
거짓


In [3]:
print(np.arange(5))

print(np.arange(5,10))

print(np.arange(5,10,2))

[0 1 2 3 4]
[5 6 7 8 9]
[5 7 9]


In [8]:
np.random.randint(5) # 0 ~ 5까지의 난수 

2

In [9]:
np.random.randint(5, 10) # 5 ~ 9까지의 난수

6

In [27]:
np.random.randint(5, size=(2, 4))

array([[2, 0, 1, 4],
       [0, 4, 3, 3]])

In [28]:
np.random.rand(5)

array([0.77509011, 0.07569747, 0.48841539, 0.31223455, 0.98396833])

In [30]:
np.random.rand(2,3)

array([[0.28425002, 0.7815078 , 0.72229649],
       [0.6389221 , 0.09813303, 0.45452018]])

In [33]:
ndarr = np.array([[6, 3], [5, 2], [4, 1]])
ndarr > 4

array([[ True, False],
       [ True, False],
       [False, False]])

In [39]:
ndarr = np.array([[6, 3], [5, 2], [4, 1]])
ndarr[ndarr > 4]

array([6, 5])

In [44]:
# 11 1부터 50까지의 난수로 된 5x6 배열을 만들고, 배열에서 짝수만 선택하여 출력하는 코드를 작성하세요.
ndarr = np.random.randint(1, 51, size=(5, 6))
print("11번 : ", ndarr)
print("짝수만 출력 : ", ndarr[ndarr%2 ==0])

11번 :  [[ 7 44 42  3 37 29]
 [46 26 16 27 40 27]
 [36 28 31  8  2  8]
 [12  1 14 34  6 30]
 [ 2 15 32 43 31 33]]
짝수만 출력 :  [44 42 46 26 16 40 36 28  8  2  8 12 14 34  6 30  2 32]
